const questionBank = [
  { question: "Jésus est-il né à Nazareth ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Faux", reference: "Matthieu 2:1" },
  { question: "Jésus a guéri combien de lépreux en une seule fois ?", type: "Complétion de Texte", options: [], correctAnswer: "10", reference: "Matthieu 8:2-4" },
  { question: "Quel âge avait la fille de Jaïrus lorsqu'elle a été ressuscitée par Jésus ?", type: "Complétion de Texte", options: [], correctAnswer: "12", reference: "Matthieu 9:18-26" },
  { question: "Combien de fois devons-nous pardonner, selon Jésus ?", type: "Complétion de Texte", options: [], correctAnswer: "77 fois 7 fois", reference: "Matthieu 18:22" },
  { question: "Combien de jours Jésus a-t-il jeûné dans le désert ?", type: "Complétion de Texte", options: [], correctAnswer: "40", reference: "Matthieu 4:2" },
  { question: "Combien de pains Jésus a-t-il utilisé pour nourrir les 5000 hommes ?", type: "Complétion de Texte", options: [], correctAnswer: "5", reference: "Matthieu 14:17" },
  { question: "Combien de frères Jésus avait-il, selon le livre de Matthieu ?", type: "Complétion de Texte",
 options: [], correctAnswer: "4", reference: "Matthieu 13:55" },
  { question: "Quel est le nom du disciple qui a trahi Jésus ?", type: "Complétion de Texte", options: [], correctAnswer: "Judas", reference: "Matthieu 26:14-16" },
  { question: "Dans quelle ville Jésus est-il né ?", type: "Complétion de Texte", options: [], correctAnswer: "Bethléem", reference: "Matthieu 2:1" },
  { question: "Quel est le premier mot du sermon sur la montagne ?", type: "Complétion de Texte", options: [], correctAnswer: "Heureux", reference: "Matthieu 5:3" },
  { question: "Combien de jours Jésus est-il resté dans le tombeau avant sa résurrection ?", type: "Complétion de Texte", options: [], correctAnswer: "3", reference: "Matthieu 12:40" },

  { question: "Combien de jours et de nuits Jésus a-t-il jeûné dans le désert ?", type: "Nombre", options: ["40", "30", "50", "Je ne sais pas"], correctAnswer: "40", reference: "Matthieu 4:2" },
  { question: "Jésus a-t-il été baptisé par Jean-Baptiste ?", type: "Oui ou Non", options: ["Oui", "Non", "Je ne sais pas"], correctAnswer: "Oui", reference: "Matthieu 3:13" },
  { question: "Jésus a-t-il multiplié les pains et les poissons pour nourrir la foule ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 14:19-21" },
  { question: "Combien de disciples Jésus avait-il ?", type: "Nombre", options: ["12", "10", "11", "Je ne sais pas"], correctAnswer: "12", reference: "Matthieu 10:2-4" },
  { question: "Le premier sermon de Jésus est appelé le Sermon sur la Montagne ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 5:1-2" },
  { question: "Combien de Béatitudes Jésus a-t-il enseignées dans le Sermon sur la Montagne ?", type: "Nombre", options: ["8", "6", "10", "Je ne sais pas"], correctAnswer: "8", reference: "Matthieu 5:3-10" },
  { question: "Jésus a-t-il marché sur l'eau ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 14:25" },
  { question: "Qui a trahi Jésus pour trente pièces d'argent ?", type: "QCM", options: ["Pierre", "Jean", "Judas", "Je ne sais pas"], correctAnswer: "Judas", reference: "Matthieu 26:14-15" },
  { question: "Jésus a-t-il ressuscité Lazare des morts ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Jean 11:1-44" },
  { question: "Combien de fois Jésus a-t-il prédit sa propre mort et résurrection ?", type: "Nombre", options: ["1", "2", "3", "Je ne sais pas"], correctAnswer: "3", reference: "Matthieu 16:21, 17:22-23, 20:17-19" },
  { question: "Jésus a-t-il chassé les marchands du temple ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 21:12" },
  { question: "Jésus a-t-il guéri un aveugle en lui touchant les yeux ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 9:27-31" },
  { question: "Combien de paraboles sont contenues dans le livre de Matthieu ?", type: "Nombre", options: ["23", "15", "30", "Je ne sais pas"], correctAnswer: "23", reference: "Divers versets" },
  { question: "Le sermon sur la montagne comprend-il le Notre Père ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 6:9-13" },
  { question: "Jésus a-t-il été tenté par le diable ?", type: "Oui ou Non", options: ["Oui", "Non", "Je ne sais pas"], correctAnswer: "Oui", reference: "Matthieu 4:1" },
  { question: "Jésus a-t-il dit : « Aimez vos ennemis » ?", type: "Oui ou Non", options: ["Oui", "Non", "Je ne sais pas"], correctAnswer: "Oui", reference: "Matthieu 5:44" },
  { question: "Combien de talents l'homme a-t-il reçu dans la parabole des talents ?", type: "QCM", options: ["1", "3", "5", "Je ne sais pas"], correctAnswer: "5", reference: "Matthieu 25:14-30" },
  { question: "Combien de vierges étaient sages dans la parabole des dix vierges ?", type: "Nombre", options: ["1", "3", "5", "Je ne sais pas"], correctAnswer: "5", reference: "Matthieu 25:2" },
  { question: "Jésus a-t-il enseigné de prier en secret ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 6:6" },
  { question: "Combien de fois devons-nous pardonner, selon Jésus ?", type: "Nombre", options: ["7 fois 9 fois", "70 fois 2 fois", "77 fois 7 fois", "Je ne sais pas"], correctAnswer: "77 fois 7 fois", reference: "Matthieu 18:22" },
  { question: "Jésus a-t-il été transfiguré sur une haute montagne ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 17:1-2" },
  { question: "Combien de fois Pierre a-t-il renié Jésus ?", type: "Nombre", options: ["1", "2", "3", "Je ne sais pas"], correctAnswer: "3", reference: "Matthieu 26:34" },
  { question: "Combien de personnes ont été nourries avec sept pains et quelques petits poissons ?", type: "Nombre", options: ["3000", "4000", "5000", "Je ne sais pas"], correctAnswer: "4000", reference: "Matthieu 15:34-38" },
  { question: "Combien de moineaux sont vendus pour un sou ?", type: "QCM", options: ["1", "2", "3", "Je ne sais pas"], correctAnswer: "2", reference: "Matthieu 10:29" },
  { question: "Combien de fois Jésus a-t-il dit : « Il est écrit » lors de la tentation dans le désert ?", type: "Nombre", options: ["1", "2", "3", "Je ne sais pas"], correctAnswer: "3", reference: "Matthieu 4:4-10" },
  { question: "Combien de fils le père avait-il dans la parabole des deux fils ?", type: "Nombre", options: ["1", "2", "3", "Je ne sais pas"], correctAnswer: "2", reference: "Matthieu 21:28-31" },
  { question: "Combien de jours Jésus a-t-il été dans le tombeau avant de ressusciter ?", type: "Nombre", options: ["1", "2", "3", "Je ne sais pas"], correctAnswer: "3", reference: "Matthieu 12:40" },
  { question: "Combien de fois Jésus a-t-il dit : « La moisson est grande, mais il y a peu d'ouvriers » ?", type: "Nombre", options: ["1", "2", "3", "Je ne sais pas"], correctAnswer: "1", reference: "Matthieu 9:37" },
  { question: "Quel est le premier livre du Nouveau Testament ?", type: "QCM", options: ["Matthieu", "Marc", "Luc", "Jean", "Je ne sais pas"], correctAnswer: "Matthieu", reference: "Matthieu 1:1" },
  { question: "Combien de jours et de nuits Jésus a-t-il jeûné dans le désert ?", type: "Complétion de Texte", options: ["40 jours et 40 nuits", "Je ne sais pas"], correctAnswer: "40 jours et 40 nuits", reference: "Matthieu 4:2" },
  { question: "Qui a baptisé Jésus ?", type: "QCM", options: ["Jean-Baptiste", "Pierre", "Paul", "Jacques", "Je ne sais pas"], correctAnswer: "Jean-Baptiste", reference: "Matthieu 3:13" },
  { question: "Jésus a-t-il multiplié les pains et les poissons pour nourrir la foule ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 14:19-21" },
  { question: "Dans quel village est né Jésus ?", type: "QCM", options: ["Nazareth", "Bethléem", "Capharnaüm", "Jérusalem", "Je ne sais pas"], correctAnswer: "Bethléem", reference: "Matthieu 2:1" },
  { question: "Combien de disciples Jésus avait-il ?", type: "QCM", options: ["10", "11", "12", "13", "Je ne sais pas"], correctAnswer: "12", reference: "Matthieu 10:2-4" },
  { question: "Quel apôtre a trahi Jésus ?", type: "QCM", options: ["Pierre", "Judas", "Jean", "Jacques", "Je ne sais pas"], correctAnswer: "Judas", reference: "Matthieu 26:14-16" },
  { question: "Quel miracle Jésus a-t-il accompli lors des noces de Cana ?", type: "QCM", options: ["Multiplication des pains", "Guérison d'un aveugle", "Transformation de l'eau en vin", "Marche sur l'eau", "Je ne sais pas"], correctAnswer: "Transformation de l'eau en vin", reference: "Jean 2:1-11" },
  { question: "Quel est le symbole de l'Esprit Saint ?", type: "QCM", options: ["Feu", "Colombe", "Eau", "Vent", "Je ne sais pas"], correctAnswer: "Colombe", reference: "Matthieu 3:16" },
  { question: "Quel est le dernier livre de la Bible ?", type: "QCM", options: ["Apocalypse", "Actes des Apôtres", "Éphésiens", "Jude", "Je ne sais pas"], correctAnswer: "Apocalypse", reference: "Apocalypse 1:1" },
  { question: "Jésus a-t-il marché sur l'eau ?", type: "Vrai ou Faux", options: ["Vrai", "Faux", "Je ne sais pas"], correctAnswer: "Vrai", reference: "Matthieu 14:25" },
  { question: "Qui est connu comme l'apôtre des Gentils ?", type: "QCM", options: ["Pierre", "Jean", "Paul", "Jacques", "Je ne sais pas"], correctAnswer: "Paul", reference: "Romains 11:13" },
  { question: "Quel apôtre a renié Jésus trois fois ?", type: "QCM", options: ["Pierre", "Jean", "Judas", "Jacques", "Je ne sais pas"], correctAnswer: "Pierre", reference: "Matthieu 26:34" },
  { question: "Quelle est la prière enseignée par Jésus ?", type: "QCM", options: ["Je vous salue Marie", "Notre Père", "Gloire à Dieu", "Credo", "Je ne sais pas"], correctAnswer: "Notre Père", reference: "Matthieu 6:9-13" },
  { question: "Quel était le métier de Matthieu avant de suivre Jésus ?", type: "QCM", options: ["Pêcheur", "Médecin", "Collecteur d'impôts", "Charpentier", "Je ne sais pas"], correctAnswer: "Collecteur d'impôts", reference: "Matthieu 9:9" },
  { question: "Combien de personnes Jésus a-t-il nourries avec cinq pains et deux poissons ?", type: "QCM", options: ["3000", "4000", "5000", "6000", "Je ne sais pas"], correctAnswer: "5000", reference: "Matthieu 14:21" },
  { question: "Quel était le nom de la mère de Jésus ?", type: "QCM", options: ["Marie", "Marthe", "Marie-Madeleine", "Elisabeth", "Je ne sais pas"], correctAnswer: "Marie", reference: "Matthieu 1:18" },
  { question: "Quel disciple est surnommé 'le disciple que Jésus aimait' ?", type: "QCM", options: ["Pierre", "Jean", "Jacques", "André", "Je ne sais pas"], correctAnswer: "Jean", reference: "Jean 13:23" },
  { question: "Quel était le nom du jardin où Jésus a été arrêté ?", type: "QCM", options: ["Gethsémani", "Éden", "Bethphagé", "Béthanie", "Je ne sais pas"], correctAnswer: "Gethsémani", reference: "Matthieu 26:36" },
  { question: "Quel est le plus grand commandement selon Jésus ?", type: "QCM", options: ["Aime ton prochain comme toi-même", "Aime le Seigneur ton Dieu", "Ne pas tuer", "Ne pas voler", "Je ne sais pas"], correctAnswer: "Aime le Seigneur ton Dieu", reference: "Matthieu 22:37-38" },
  { question: "Quel était le nom du fleuve où Jésus a été baptisé ?", type: "QCM", options: ["Nil", "Jourdain", "Euphrate", "Tigre", "Je ne sais pas"], correctAnswer: "Jourdain", reference: "Matthieu 3:13" },
  { question: "Qui est le père de Jean-Baptiste ?", type: "QCM", options: ["Joseph", "Zacharie", "Siméon", "Lévi", "Je ne sais pas"], correctAnswer: "Zacharie", reference: "Luc 1:13" },
  { question: "Qui a demandé la tête de Jean-Baptiste ?", type: "QCM", options: ["Hérodiade", "Salomé", "Hérode", "Pilate", "Je ne sais pas"], correctAnswer: "Salomé", reference: "Matthieu 14:8" },
  { question: "Qui est le frère de Marthe ?", type: "QCM", options: ["Pierre", "Lazare", "Jean", "Jacques", "Je ne sais pas"], correctAnswer: "Lazare", reference: "Jean 11:1-2" },
  { question: "Combien de tentations Jésus a-t-il subies dans le désert ?", type: "QCM", options: ["1", "2", "3", "4", "Je ne sais pas"], correctAnswer: "3", reference: "Matthieu 4:1-11" },
  { question: "Quel est le signe de l'alliance entre Dieu et Noé ?", type: "QCM", options: ["Arc-en-ciel", "Colombe", "Olive", "Feu", "Je ne sais pas"], correctAnswer: "Arc-en-ciel", reference: "Genèse 9:13" },
  { question: "Qui a écrit les Actes des Apôtres ?", type: "QCM", options: ["Paul", "Jean", "Pierre", "Luc", "Je ne sais pas"], correctAnswer: "Luc", reference: "Actes 1:1" },
  { question: "Combien de chapitres contient le livre de l'Apocalypse ?", type: "QCM", options: ["20", "21", "22", "23", "Je ne sais pas"], correctAnswer: "22", reference: "Apocalypse 22:21" },
  { question: "Quel apôtre a été le premier martyr ?", type: "QCM", options: ["Pierre", "Paul", "Jacques", "Étienne", "Je ne sais pas"], correctAnswer: "Étienne", reference: "Actes 7:59-60" },
  { question: "Combien de fruits de l'Esprit sont mentionnés dans Galates ?", type: "QCM", options: ["7", "8", "9", "10", "Je ne sais pas"], correctAnswer: "9", reference: "Galates 5:22-23" },
  { question: "Quelle est la première béatitude ?", type: "QCM", options: ["Bienheureux les pauvres en esprit", "Bienheureux ceux qui pleurent", "Bienheureux les doux", "Bienheureux ceux qui ont faim et soif de justice", "Je ne sais pas"], correctAnswer: "Bienheureux les pauvres en esprit", reference: "Matthieu 5:3" },
  { question: "Qui a construit l'arche ?", type: "QCM", options: ["Noé", "Moïse", "Abraham", "Élie", "Je ne sais pas"], correctAnswer: "Noé", reference: "Genèse 6:14" },
  { question: "Quel prophète a été avalé par un grand poisson ?", type: "QCM", options: ["Jonas", "Ésaïe", "Ézéchiel", "Jérémie", "Je ne sais pas"], correctAnswer: "Jonas", reference: "Jonas 1:17" },
  { question: "Quel est le premier commandement ?", type: "QCM", options: ["Tu n'auras pas d'autres dieux devant moi", "Tu ne feras pas d'idoles", "Tu ne prendras pas le nom de l'Éternel en vain", "Souviens-toi du jour du repos", "Je ne sais pas"], correctAnswer: "Tu n'auras pas d'autres dieux devant moi", reference: "Exode 20:3" },
  { question: "Combien de fois Jésus a-t-il prédit sa mort et sa résurrection ?", type: "QCM", options: ["1", "2", "3", "4", "Je ne sais pas"], correctAnswer: "3", reference: "Matthieu 16:21" },
  { question: "Quel était le nom du géant vaincu par David ?", type: "QCM", options: ["Goliath", "Og", "Sihon", "Anak", "Je ne sais pas"], correctAnswer: "Goliath", reference: "1 Samuel 17:4" },
  { question: "Quel est le nom hébreu de Jésus ?", type: "QCM", options: ["Yeshua", "Yohanan", "Yitzhak", "Yaakov", "Je ne sais pas"], correctAnswer: "Yeshua", reference: "Matthieu 1:21" },
  { question: "Quel est le signe de l'alliance entre Dieu et Abraham ?", type: "QCM", options: ["Circoncision", "Sabbat", "Arc-en-ciel", "Sacrifice", "Je ne sais pas"], correctAnswer: "Circoncision", reference: "Genèse 17:11" },
  { question: "Quel est le dernier mot de la Bible ?", type: "QCM", options: ["Amen", "Alléluia", "Fin", "Grâce", "Je ne sais pas"], correctAnswer: "Amen", reference: "Apocalypse 22:21" },
  { question: "Quel est le nom du premier martyr chrétien ?", type: "QCM", options: ["Étienne", "Jacques", "Jean", "Pierre", "Je ne sais pas"], correctAnswer: "Étienne", reference: "Actes 7:59-60" },
  { question: "Quel est le premier miracle de Jésus ?", type: "QCM", options: ["Transformation de l'eau en vin", "Guérison d'un aveugle", "Multiplication des pains", "Marche sur l'eau", "Je ne sais pas"], correctAnswer: "Transformation de l'eau en vin", reference: "Jean 2:1-11" },
  { question: "Quel est le nom de la mer où Jésus a marché sur l'eau ?", type: "QCM", options: ["Mer de Galilée", "Mer Morte", "Mer Rouge", "Mer Méditerranée", "Je ne sais pas"], correctAnswer: "Mer de Galilée", reference: "Matthieu 14:25" },
  { question: "Quel est le nom de l'apôtre qui a trahi Jésus ?", type: "QCM", options: ["Judas", "Pierre", "Jean", "Jacques", "Je ne sais pas"], correctAnswer: "Judas", reference: "Matthieu 26:14-16" },
];

export default questionBank;
